# Generated by Django 4.0.3 on 2022-03-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('ERKAK', 'Erkak'), ('AYOL', 'Ayol')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('imdb', models.URLField()),
                ('genre', models.CharField(max_length=150)),
                ('actors', models.ManyToManyField(related_name='actors', to='studio.actor')),
            ],
        ),
    ]
