# Generated by Django 4.0.3 on 2022-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_actor_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='studio.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actors', to='studio.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('DRAMA', 'Drama'), ('KOMSEDIYA', 'Komediya'), ('DETIKTIV', 'Detiktiv'), ('ROMANTIKA', 'Romantika'), ('FANTASTIK', 'Fantastik'), ('JANGARI', 'Jangari')], max_length=9),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.IntegerField(),
        ),
    ]
