name: Django CD

on:
  push:
    branches: [master]

jobs:
  build:
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    runs-on: debian-9
    needs: build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 46.101.96.67
          passphrase: 12345
          key: ${{ secrets.KEY }}
          username: root
          script: |
            cd movieapi
            git pull
            systemctl restart gunicorn.service